version: "3.9"
services:
  postgres:
    image: postgres:13-alpine
    container_name: simple_bank_psql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
    expose:
      - 5432